### ISSUE TITLE
Unread items in  yarr v2.4 vs master

### ISSUE THREAD

**Issue by grigio** [nkanaev/yarr#167]
I tried the master it seems some items are showed again even if i read them.. Unfortunatly i didn;t find a way more specific to reproduce the bug.
Now I rolled back do v2.4

**Comment by nkanaev** [comment]
There were [no changes in handling article statuses](https://github.com/nkanaev/yarr/compare/v2.4..master) since v2.4.

What you're experience may be the case of source feeds changing their guids. That results it duplicate feeds appearing in the feed's "All" tab (see [here](https://github.com/nkanaev/yarr/issues/87#issuecomment-1950261906)).

If you have a different experience, please let me know and I'll re-open the ticket.
