### ISSUE TITLE
No feeds found at the given url.

### ISSUE THREAD

**Issue by ilaer** [nkanaev/yarr#21]
![深度截图_选择区域_20200929145319](https://user-images.githubusercontent.com/5914968/94523437-c67c8800-0263-11eb-98c7-4da93f1b232d.png)
http://feed.cnblogs.com/blog/u/782/rss/
http://feed.cnblogs.com/blog/u/295481/rss/

add error

**Comment by ilaer** [comment]
the same.
https://www.xiaohui.com/rss/

**Comment by ilaer** [comment]
the same.
https://studygolang.com/feed.xml

**Comment by nkanaev** [comment]
thanks for the report! i'll try get it fixed before the next release.

**Comment by nkanaev** [comment]
feeds with byte order marks:

http://feed.cnblogs.com/blog/u/782/rss/
http://feed.cnblogs.com/blog/u/295481/rss/

fixed in: https://github.com/nkanaev/gofeed/commit/8d24d3ab5d846617720755ce11a21c07916b4e8d

---

timing out:

https://www.xiaohui.com/rss/
https://studygolang.com/feed.xml

fixed in : https://github.com/nkanaev/yarr/commit/8007853a9a15f0d6efb1db0539501d74e49c6cc0
