### ISSUE TITLE
Support tray icon on Linux

### ISSUE THREAD

**Issue by matklad** [nkanaev/yarr#22]
I see that support for tray icons on linux was removed shortly before release. I personally would love to see this feature back :)

**Comment by nkanaev** [comment]
I'd love to have tight integration with the linux desktop as well. given that, the best option to do so probably is to ship distribution-specific packages (deb, rpm).

unfortunately, due to limited time & resources, i won't be able to ship/test it. anyone who'd like to contribute/maintain that part are always welcome.

**Comment by nkanaev** [comment]
there's little interest in the desktop integration (linux users seem to mostly prefer self-hosting). closing it now.

happy to reopen the ticket for contributors.
