### ISSUE TITLE
Suggestion: Fever API support

### ISSUE THREAD

**Issue by SMylk** [nkanaev/yarr#38]
So it can sync with online feed readers.

**Comment by nkanaev** [comment]
i considered that in the past, but didn't get it finished due to lack of widespead adoption in the open-source community. as of 2020 there wasn't a decent RSS reader for Android, with majority of clients being mostly on ios/macos. so my focus shifted to the responsive mobile design.

the work i've done so far is available in `fever` branch, but requires extensive testing with the existing clients, and might be missing few features.

**Comment by nkanaev** [comment]
fever api won't be shipped. there are no open source & supported apps to test the api on.

contributors/maintainers are welcome though. give me a shout and i'll be happy to reopen the ticket.

**Comment by verahawk** [comment]
@nkanaev have you seen this app: https://github.com/bubelov/news? Sadly it only supports Nextcloud and Miniflux APIs as of now.
