### ISSUE TITLE
Suggestion: Allow to edit feed urls

### ISSUE THREAD

**Issue by 0xJes** [nkanaev/yarr#53]
You can edit feed names and arrange them, but you can't edit the feed URL (after adding them), I think this is a basic feature of feed readers.

**Comment by nkanaev** [comment]
i disagree that editing the feed url is a basic feature. at least netnewswire & reeder on macos do not give you that option.

i've considered adding the ability to edit feed source, but decided not to due to the rarity of the issue. adding the updated feed url (and optionally deleting the old one) works fine most of the time.
