### ISSUE TITLE
Add night mode

### ISSUE THREAD

**Issue by hmsjy2017** [nkanaev/yarr#66]
Yarr currently does not support night mode (I didn't find it anyway). It is dazzling to watch the screen at night. I hope to add night mode. In addition, I also hope to add a login function.

**Comment by nkanaev** [comment]
1. You can switch to dark mode in the article settings (available in `Appearance` settings). Automatic switch based on the browser preferences will not be implemented. 
2. Authentication is available if `-auth` param is set.

**Comment by nkanaev** [comment]
The main reasoning was because the app has 3 themes (light/black/sepia), so I didn't want to impose which theme to default to based on OS/browser mode. Say, if a browser is set to dark mode, what if a user prefers sepia theme for black?

There was also uncertainty on how to make it work with OS-level `auto` mode. For that scenario, a choice of black theme may make sense for dark mode, but what about light mode? Should it be light or sepia?

With all that, I didn't want to overthink the configuration, and stuck with the manual choice. I'm happy to reopen the issue if anyone can come up with an idea on how to make it all work seamlessly, something which would take into account all the possible use cases.
