### ISSUE TITLE
Reddit rss feeds stop working after last update

### ISSUE THREAD

**Issue by samcro1967** [nkanaev/yarr#96]
Seems like the update a few days ago effected Reddit RSS links.

[Reddit Link](https://www.reddit.com/r/selfhosted.rss)

![image](https://user-images.githubusercontent.com/2319445/167300433-1cc39f7e-a4f7-4cd0-a7a5-b6fbd498eb88.png)

![image](https://user-images.githubusercontent.com/2319445/167300446-f436499f-c9f1-4de4-9034-cb26d1556746.png)

**Comment by nkanaev** [comment]
this is very weird.

It seems that either rate-limiting or request blocking is at play. The former happens when there are too many requests to the server. I've seen the latter when "user-agent" header is not present.

In my case it's `403 Blocked`. It is possible Reddit is experiencing internal issues.

**Comment by nkanaev** [comment]
Seems to be working now.

**Comment by mokahless** [comment]
I just want to note for the record that I had this exact issue last happen in November. If it is going to re-occur, we at least need a workaround. Sorry, I've been deleting and re-commenting. I hope this is the last time and the most appropriate thread for me to post in.

Linking #1472 #1628 #1432 as related.

I think we need some kind of checkbox to force certain feeds to not stop checking after an error, or perhaps have them on a timeout we can configure, rather than just have them permanently give up.
